algoritmo "semnome"
// Função :
// Autor :
// Data : 18/11/2022
// Seção de Declarações 
var
n,m1,m2,digitado: inteiro
res: inteiro
nome: caractere
inicio
// Seção de Comandos
escreval ("Informe seu nome:")
leia (nome)
escreval("Você irá digitar 10 números")
escreval("Para saber qual o resultado ao quadrado")
m1<- digitado
para n de 1 ate 10 faca
escreval("Informe o Número")
leia (Digitado)

res <-(digitado*digitado)

escreval("O Resultado é:",res)

fimpara

fimalgoritmo
